# Config file for automatic testing at travis-ci.com

stages:
  - lint
  - test

language: python

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

jobs:
  include:
    - stage: lint
      python: 3.8
      env: TOXENV=flake8
    - python: 3.8
      env: TOXENV=format
    - python: 3.8
      env: TOXENV=mypy
    - python: 3.8
      env: TOXENV=docs

    - stage: test
      python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
